#ifndef DISASM_REG_H
#define DISASM_REG_H

typedef enum {
    DISASM_REG_NONE = 0,

    // --- 8-bit Registers (Legacy & Uniform/Extended) ---
    DISASM_REG_AL, DISASM_REG_CL, DISASM_REG_DL, DISASM_REG_BL,
    DISASM_REG_AH, DISASM_REG_CH, DISASM_REG_DH, DISASM_REG_BH,
    DISASM_REG_SPL, DISASM_REG_BPL, DISASM_REG_SIL, DISASM_REG_DIL,
    DISASM_REG_R8B, DISASM_REG_R9B, DISASM_REG_R10B, DISASM_REG_R11B, DISASM_REG_R12B, DISASM_REG_R13B, DISASM_REG_R14B, DISASM_REG_R15B,

    // --- 16-bit Registers ---
    DISASM_REG_AX, DISASM_REG_CX, DISASM_REG_DX, DISASM_REG_BX, DISASM_REG_SP, DISASM_REG_BP, DISASM_REG_SI, DISASM_REG_DI,
    DISASM_REG_R8W, DISASM_REG_R9W, DISASM_REG_R10W, DISASM_REG_R11W, DISASM_REG_R12W, DISASM_REG_R13W, DISASM_REG_R14W, DISASM_REG_R15W,

    // --- 32-bit Registers ---
    DISASM_REG_EAX, DISASM_REG_ECX, DISASM_REG_EDX, DISASM_REG_EBX, DISASM_REG_ESP, DISASM_REG_EBP, DISASM_REG_ESI, DISASM_REG_EDI,
    DISASM_REG_R8D, DISASM_REG_R9D, DISASM_REG_R10D, DISASM_REG_R11D, DISASM_REG_R12D, DISASM_REG_R13D, DISASM_REG_R14D, DISASM_REG_R15D,

    // --- 64-bit Registers ---
    DISASM_REG_RAX, DISASM_REG_RCX, DISASM_REG_RDX, DISASM_REG_RBX, DISASM_REG_RSP, DISASM_REG_RBP, DISASM_REG_RSI, DISASM_REG_RDI,
    DISASM_REG_R8,  DISASM_REG_R9,  DISASM_REG_R10, DISASM_REG_R11, DISASM_REG_R12, DISASM_REG_R13, DISASM_REG_R14, DISASM_REG_R15,

    // --- Special ---
    DISASM_REG_RIP,

    // --- Segment ---
    DISASM_REG_ES, DISASM_REG_CS, DISASM_REG_SS, DISASM_REG_DS, DISASM_REG_FS, DISASM_REG_GS,

    // --- FPU ---
    DISASM_REG_ST,
    DISASM_REG_ST0, DISASM_REG_ST1, DISASM_REG_ST2, DISASM_REG_ST3, DISASM_REG_ST4, DISASM_REG_ST5, DISASM_REG_ST6, DISASM_REG_ST7,

    // --- SIMD ---
    DISASM_REG_MM0, DISASM_REG_MM1, DISASM_REG_MM2, DISASM_REG_MM3,
    DISASM_REG_MM4, DISASM_REG_MM5, DISASM_REG_MM6, DISASM_REG_MM7,

    DISASM_REG_XMM0, DISASM_REG_XMM1, DISASM_REG_XMM2, DISASM_REG_XMM3,
    DISASM_REG_XMM4, DISASM_REG_XMM5, DISASM_REG_XMM6, DISASM_REG_XMM7,
    DISASM_REG_XMM8, DISASM_REG_XMM9, DISASM_REG_XMM10, DISASM_REG_XMM11,
    DISASM_REG_XMM12, DISASM_REG_XMM13, DISASM_REG_XMM14, DISASM_REG_XMM15,
} Disasm_Reg;

u8* disasm_reg_stringify(Disasm_Reg reg);

#endif
